spring:
  application:
    name: gateway-service
  config:
    import: optional:file:.env[.properties]
  
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/api/transaction/**

eureka:
  client:
    service-url:
      defaultZone: ${LOCAL_EURECA_URL}
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080